### ISSUE TITLE
xml_recorder problem when extracting text using XML &gt; or &lt; entities

### ISSUE THREAD

**Issue by davidrissato** [StevenLooman/saxpath#17]
When you try to extract a piece of XML that contains entities inside:

```XML
<item>
   <description>Must support &gt; and &lt; entities</description>
</item>
```

It generates an invalid XML representation like this one:
```XML
<item>
   <description>Must support < and > entities</description>
</item>
```

To fix to this problem, it requires just a simple call to `escapeXml` at `onText` event in xml_recorder.js (line 57).

```DIFF
@@ -53,9 +53,9 @@
 XmlRecorder.prototype.onText = function (text) {
     var id;
     for (id in this.streams) {
         if (this.streams.hasOwnProperty(id)) {
-            this.streams[id] += text;
+            this.streams[id] += escapeXml(text);
         }
     }
 };
 
```

**Comment by StevenLooman** [comment]
Thank you for reporting and fixing this. Pull request has been merged, I'll release a new version soon.

**Comment by StevenLooman** [comment]
0.6.5 was just published to npm.
